name: Build TrollSpeed TIPA

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: beerpiss/theos-action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Build TIPA
        run: |
          make clean package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload TIPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrollSpeed-TIPA
          path: packages/*.tipa
